server:
    port: 8080
    servlet:
        context-path: /undecemberTest

spring:
    thymeleaf:
        cache: false
        prefix: classpath:/templates/
        suffix: .html
    # web:
    #     resources:
    #         static-locations: classpath:/static/